// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaDesarrolloDeadlockCore.Context;

namespace PruebaDesarrolloDeadlockCore.Migrations
{
    [DbContext(typeof(PruebaDesarrolloDeadlockContext))]
    [Migration("20200815171241_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaDesarrolloDeadlockCore.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PosicionId")
                        .HasColumnType("int");

                    b.Property<int>("Telefono1")
                        .HasColumnType("int");

                    b.Property<int>("Telefono2")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("PosicionId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("PruebaDesarrolloDeadlockCore.Models.Posicion", b =>
                {
                    b.Property<int>("PosicionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PosicionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PosicionId");

                    b.ToTable("Posicións");
                });

            modelBuilder.Entity("PruebaDesarrolloDeadlockCore.Models.Empleado", b =>
                {
                    b.HasOne("PruebaDesarrolloDeadlockCore.Models.Posicion", "Posicion")
                        .WithMany("Empleados")
                        .HasForeignKey("PosicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
